language: java
matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      env: NAME="Trusty"
    - os: linux
      sudo: required
      dist: xenial
      env: NAME="Xenial"
    - os: linux
      sudo: required
      dist: precise
      env: NAME="Precise"

before_install:
- sudo apt-get -qq update

install:
- sudo apt-get -qq install git

script:
- bash build-onos.sh
- sudo bash install-onos.sh
- sudo bash test-onos.sh

notifications:
  email:
      on_success: never
      # More details: https://docs.travis-ci.com/user/notifications#Configuring-email-notifications
